# Generated by Django 4.2.3 on 2023-10-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fifth_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litle_title', models.CharField(max_length=50, verbose_name='Пред заголовок')),
                ('main_title', models.CharField(max_length=50, verbose_name='Главный заголовок')),
                ('advantage', models.CharField(default='Лучшее', max_length=50, verbose_name='Преимущество курса')),
                ('price', models.CharField(default=123, max_length=50, verbose_name='Стоимость курса')),
                ('description_1', models.CharField(default='Описание', max_length=50, verbose_name='Первое описание')),
                ('name', models.CharField(default='Название', max_length=50, verbose_name='Название курса')),
                ('description_2', models.CharField(default='Описание', max_length=50, verbose_name='Подробное описание курса')),
                ('button', models.CharField(default='Кнопка', max_length=50, verbose_name='Кнопка')),
            ],
            options={
                'verbose_name': 'Пятый раздел-Стоимость курсов',
                'verbose_name_plural': 'Пятый раздел-Стоимость курсов',
            },
        ),
        migrations.CreateModel(
            name='First_Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litle_title', models.CharField(max_length=50, verbose_name='Пред заголовок')),
                ('main_title', models.CharField(max_length=50, verbose_name='Главный заголовок')),
                ('button_1', models.CharField(max_length=50, verbose_name='Первая кнопка')),
                ('button_2', models.CharField(max_length=50, verbose_name='Вторая кнопка')),
            ],
            options={
                'verbose_name': 'Первый раздел-Название курсов',
                'verbose_name_plural': 'Первый раздел-Название курсов',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=50, verbose_name='Главный заголовок')),
                ('url_1', models.URLField(verbose_name='Первый сайт')),
                ('url_2', models.URLField(verbose_name='Второй сайт')),
                ('url_3', models.URLField(verbose_name='Третий сайт')),
            ],
            options={
                'verbose_name': 'Футер сайта',
                'verbose_name_plural': 'Футер сайта',
            },
        ),
        migrations.CreateModel(
            name='Forth_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(blank=True, default='Заголовок', max_length=50, null=True, verbose_name='Главный заголовок')),
                ('litle_title', models.CharField(default=None, max_length=50, verbose_name='Пред заголовок')),
                ('name', models.CharField(default=None, max_length=50, verbose_name='Имя ментора')),
                ('experience', models.TextField(default='Опыт', max_length=3000, verbose_name='Опыт ментора')),
                ('image', models.ImageField(default='Картинка', upload_to='', verbose_name='Фото ментора')),
            ],
            options={
                'verbose_name': 'Четвёртый раздел-Менторы',
                'verbose_name_plural': 'Четвёртый раздел-Менторы',
            },
        ),
        migrations.CreateModel(
            name='Second_Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=50, verbose_name='Заголовок')),
                ('description', models.TextField(default=None, max_length=3000, verbose_name='Описание')),
                ('button', models.CharField(default='Кнопка', max_length=50, verbose_name='Кнопка')),
            ],
            options={
                'verbose_name': 'Второй раздел-Подробное описание',
                'verbose_name_plural': 'Второй раздел-Подробное описание',
            },
        ),
        migrations.CreateModel(
            name='Seventh_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litle_title', models.CharField(max_length=50, verbose_name='Пред заголовок')),
                ('main_title', models.CharField(max_length=50, verbose_name='Главный заголовок')),
                ('image_1', models.ImageField(default='some picture', upload_to='', verbose_name='Фото организации')),
                ('image_2', models.ImageField(default='some picture', upload_to='', verbose_name='Фото организации')),
            ],
            options={
                'verbose_name': 'Седьмой раздел-Помошники в организации курсов',
                'verbose_name_plural': 'Седьмой раздел-Помошники в организации курсов',
            },
        ),
        migrations.CreateModel(
            name='Sixth_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litle_title', models.CharField(max_length=50, verbose_name='Пред заголовок')),
                ('main_title_1', models.CharField(max_length=50, verbose_name='Левый заголовок')),
                ('description_1', models.CharField(max_length=50, verbose_name='Леове описание')),
                ('main_title_2', models.CharField(max_length=50, verbose_name='Правый заголовок')),
                ('description_2', models.CharField(max_length=50, verbose_name='Правое описание')),
                ('button', models.CharField(max_length=50, verbose_name='Кнопка')),
            ],
            options={
                'verbose_name': 'Шестой раздел-Дополнительная информация',
                'verbose_name_plural': 'Шестой раздел-Дополнительная информация',
            },
        ),
        migrations.CreateModel(
            name='Third_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litle_title', models.CharField(default=None, max_length=50, verbose_name='Пред заголовок')),
                ('main_title', models.CharField(default=None, max_length=50, verbose_name='Главный заголовок')),
                ('number_1', models.IntegerField(default=None, verbose_name='Первая цифра')),
                ('description_1', models.CharField(default=None, max_length=50, verbose_name='Первое описание')),
                ('number_2', models.IntegerField(default=None, verbose_name='Вторая цифра')),
                ('description_2', models.CharField(default=None, max_length=50, verbose_name='Второе описание')),
                ('number_3', models.IntegerField(default=None, verbose_name='Третья цифра')),
                ('description_3', models.CharField(default=None, max_length=50, verbose_name='Третье описание')),
            ],
            options={
                'verbose_name': 'Третий раздел-Статистика обучающихся',
                'verbose_name_plural': 'Третий раздел-Статистика обучающихся',
            },
        ),
    ]
