# Generated by Django 4.2.3 on 2023-10-02 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='third_title',
            old_name='description_1',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='third_title',
            old_name='number_1',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='third_title',
            name='description_2',
        ),
        migrations.RemoveField(
            model_name='third_title',
            name='description_3',
        ),
        migrations.RemoveField(
            model_name='third_title',
            name='number_2',
        ),
        migrations.RemoveField(
            model_name='third_title',
            name='number_3',
        ),
    ]
