# Generated by Django 4.2.3 on 2023-10-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_description_1_third_title_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='third_title',
            old_name='description',
            new_name='description_1',
        ),
        migrations.RenameField(
            model_name='third_title',
            old_name='number',
            new_name='number_1',
        ),
        migrations.AddField(
            model_name='third_title',
            name='description_2',
            field=models.CharField(default=None, max_length=50, verbose_name='Второе описание'),
        ),
        migrations.AddField(
            model_name='third_title',
            name='description_3',
            field=models.CharField(default=None, max_length=50, verbose_name='Третье описание'),
        ),
        migrations.AddField(
            model_name='third_title',
            name='description_4',
            field=models.CharField(default=None, max_length=50, verbose_name='Четвёртое описание'),
        ),
        migrations.AddField(
            model_name='third_title',
            name='number_2',
            field=models.IntegerField(default=None, verbose_name='Вторая цифра'),
        ),
        migrations.AddField(
            model_name='third_title',
            name='number_3',
            field=models.IntegerField(default=None, verbose_name='Третья цифра'),
        ),
        migrations.AddField(
            model_name='third_title',
            name='number_4',
            field=models.IntegerField(default=None, verbose_name='Четвёртая цифра'),
        ),
    ]
