# Generated by Django 4.2.3 on 2023-10-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_rename_description_third_title_description_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fifth_title',
            name='advantage',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='Преимущество курса'),
        ),
        migrations.AlterField(
            model_name='fifth_title',
            name='button',
            field=models.CharField(default=None, max_length=50, verbose_name='Кнопка'),
        ),
        migrations.AlterField(
            model_name='fifth_title',
            name='description_1',
            field=models.CharField(default=None, max_length=50, verbose_name='Первое описание'),
        ),
        migrations.AlterField(
            model_name='fifth_title',
            name='description_2',
            field=models.CharField(default=None, max_length=50, verbose_name='Подробное описание курса'),
        ),
        migrations.AlterField(
            model_name='fifth_title',
            name='name',
            field=models.CharField(default=None, max_length=50, verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='forth_title',
            name='experience',
            field=models.TextField(default=None, max_length=3000, verbose_name='Опыт ментора'),
        ),
        migrations.AlterField(
            model_name='forth_title',
            name='image',
            field=models.ImageField(default=None, upload_to='', verbose_name='Фото ментора'),
        ),
        migrations.AlterField(
            model_name='forth_title',
            name='main_title',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Главный заголовок'),
        ),
        migrations.AlterField(
            model_name='second_title',
            name='button',
            field=models.CharField(default=None, max_length=50, verbose_name='Кнопка'),
        ),
        migrations.AlterField(
            model_name='seventh_title',
            name='image_1',
            field=models.ImageField(default=None, upload_to='', verbose_name='Фото организации'),
        ),
        migrations.AlterField(
            model_name='seventh_title',
            name='image_2',
            field=models.ImageField(default=None, upload_to='', verbose_name='Фото организации'),
        ),
    ]
