# Generated by Django 4.2.3 on 2023-10-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_fifth_title_advantage_alter_fifth_title_button_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_title', models.CharField(max_length=50, verbose_name='Заголовок третьего раздела')),
                ('first_litle_title', models.CharField(max_length=50, verbose_name='Пред заголовок третьего раздела')),
                ('second_title', models.CharField(max_length=50, verbose_name='Заголовок четвёртого раздела')),
                ('third_title', models.CharField(max_length=50, verbose_name='Заголовок пятого раздела')),
                ('third_litle_title', models.CharField(max_length=50, verbose_name='Пред заголовок пятого раздела')),
                ('forth_title', models.CharField(max_length=50, verbose_name='Заголовок седьмого раздела')),
                ('forth_litle_title', models.CharField(max_length=50, verbose_name='Пред заголовок седьмого раздела')),
            ],
            options={
                'verbose_name': 'Заголовки разделов',
                'verbose_name_plural': 'Заголовки разделов',
            },
        ),
        migrations.AlterField(
            model_name='fifth_title',
            name='advantage',
            field=models.CharField(default=None, max_length=50, verbose_name='Преимущество курса'),
        ),
    ]
