# Generated by Django 4.2.3 on 2023-10-02 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_title_alter_fifth_title_advantage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='third_title',
            old_name='number_1',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='fifth_title',
            name='litle_title',
        ),
        migrations.RemoveField(
            model_name='fifth_title',
            name='main_title',
        ),
        migrations.RemoveField(
            model_name='forth_title',
            name='main_title',
        ),
        migrations.RemoveField(
            model_name='seventh_title',
            name='litle_title',
        ),
        migrations.RemoveField(
            model_name='seventh_title',
            name='main_title',
        ),
        migrations.RemoveField(
            model_name='third_title',
            name='litle_title',
        ),
        migrations.RemoveField(
            model_name='third_title',
            name='main_title',
        ),
    ]
