# Generated by Django 4.2.3 on 2023-10-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_rename_number_1_third_title_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seventh_title',
            name='litle_title',
            field=models.CharField(default='Ниже выберите фото или логотипы организаций помошников', max_length=50, verbose_name='Подсказка'),
        ),
    ]
