# Generated by Django 4.2.3 on 2023-10-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_seventh_title_litle_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seventh_title',
            name='litle_title',
            field=models.TextField(default='Ниже выберите фото или логотипы организаций помошников ("Это поля необязательно к заполнению)', max_length=500, verbose_name='Подсказка'),
        ),
    ]
