# Generated by Django 4.2.3 on 2023-10-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_seventh_title_litle_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='third_title',
            name='description_1',
        ),
        migrations.RemoveField(
            model_name='third_title',
            name='description_2',
        ),
        migrations.RemoveField(
            model_name='third_title',
            name='description_3',
        ),
        migrations.RemoveField(
            model_name='third_title',
            name='description_4',
        ),
        migrations.RemoveField(
            model_name='third_title',
            name='number_2',
        ),
        migrations.RemoveField(
            model_name='third_title',
            name='number_3',
        ),
        migrations.RemoveField(
            model_name='third_title',
            name='number_4',
        ),
        migrations.AddField(
            model_name='third_title',
            name='description',
            field=models.CharField(default=None, max_length=50, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='third_title',
            name='number',
            field=models.IntegerField(default=None, verbose_name='Цифра'),
        ),
    ]
