# Generated by Django 4.2.3 on 2023-10-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_remove_third_title_description_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkOptionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionOne', models.CharField(blank=True, help_text='Ссылки под первым заголовком', max_length=100, verbose_name='Ссылки блок 1')),
                ('optionTwo', models.CharField(blank=True, help_text='Ссылки под вторым заголовком', max_length=100, verbose_name='Ссылки блок 2')),
                ('optionThree', models.CharField(blank=True, help_text='Ссылки под третьем заголовком', max_length=100, verbose_name='Ссылки блок 3')),
            ],
            options={
                'verbose_name': 'Ссылки под заголовком в блоке ссылок',
                'verbose_name_plural': 'Ссылки под заголовком в блоке ссылок',
            },
        ),
    ]
