# Generated by Django 4.2.3 on 2023-10-02 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_eighth_title_delete_linkoptionblock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eighth_title',
            options={'verbose_name': '8) Восьмой раздел-Ссылки навигации', 'verbose_name_plural': '8) Восьмой раздел-Ссылки навигации'},
        ),
        migrations.AlterModelOptions(
            name='fifth_title',
            options={'verbose_name': '5) Пятый раздел-Стоимость курсов', 'verbose_name_plural': '5) Пятый раздел-Стоимость курсов'},
        ),
        migrations.AlterModelOptions(
            name='first_title',
            options={'verbose_name': '1) Первый раздел-Название курсов', 'verbose_name_plural': '1) Первый раздел-Название курсов'},
        ),
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': '9) Футер сайта', 'verbose_name_plural': '9) Футер сайта'},
        ),
        migrations.AlterModelOptions(
            name='forth_title',
            options={'verbose_name': '4) Четвёртый раздел-Менторы', 'verbose_name_plural': '4) Четвёртый раздел-Менторы'},
        ),
        migrations.AlterModelOptions(
            name='second_title',
            options={'verbose_name': '2) Второй раздел-Подробное описание', 'verbose_name_plural': '2)Второй раздел-Подробное описание'},
        ),
        migrations.AlterModelOptions(
            name='seventh_title',
            options={'verbose_name': '7) Седьмой раздел-Помошники в организации курсов', 'verbose_name_plural': '7) Седьмой раздел-Помошники в организации курсов'},
        ),
        migrations.AlterModelOptions(
            name='sixth_title',
            options={'verbose_name': '6) Шестой раздел-Дополнительная информация', 'verbose_name_plural': '6) Шестой раздел-Дополнительная информация'},
        ),
        migrations.AlterModelOptions(
            name='third_title',
            options={'verbose_name': '3) Третий раздел-Статистика обучающихся', 'verbose_name_plural': '3)Третий раздел-Статистика обучающихся'},
        ),
    ]
